name: quizeapp
description: Search Hadees Admin Panel Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # COMMON
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  nb_utils: ^7.0.8
  mobx: ^2.5.0

  flutter_mobx: ^2.3.0
  google_fonts: ^6.2.1
  flutter_vector_icons: ^2.0.0
  cached_network_image: ^3.4.1
  url_strategy: ^0.3.0
  firebase_ui_localizations: ^1.13.0

  # PUSH NOTIFICATION
  onesignal_flutter: ^5.2.9

  # FIREBASE PACKAGES
  #  firebase_core: ^1.2.0
  #  firebase_auth: ^3.11.2
  #  cloud_firestore: ^3.5.1
  #  firebase_storage: ^10.3.11
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  #firebase_crashlytics: ^1.0.0
  firebase_messaging:  ^15.1.6
  google_sign_in: ^6.2.2
  #  youtube_player_flutter: ^8.0.0
  #  youtube_player_iframe: ^2.2.2
  youtube_player_iframe: ^5.2.1
  number_pagination: ^1.1.6
  equatable: ^2.0.7
  #  video_player: ^2.8.2
  #  path_provider: ^2.1.3
  #  dio: ^5.0.0
  #  permission_handler: ^11.3.1
  shared_preferences: ^2.3.5
  #google_mobile_ads: ^0.11.0+3

#  pagination: ^1.0.3+1

dependency_overrides:
  #  firebase_core_platform_interface: 4.5.1
  #  cloud_firestore_web: 2.6.5
  #  firebase_core_web: 2.0.0
  flutter_localization: ^0.3.0
  firebase_storage_web: ^3.10.6
  intl: ^0.20.1
  win32: ^5.10.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  mobx_codegen: ^2.0.1+3
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins-Black.ttf
        weight: 900

  - family: UrduFonts
    fonts:
      - asset: assets/fonts/Jameel_noori_nastaleeq.ttf

  - family: UrduFonts2
    fonts:
      - asset: assets/fonts/nafees_naksh.ttf

  - family: ArabicFonts
    fonts:
      - asset: assets/fonts/muhammadi_bold_urdu_finle.ttf

  - family: NotoNastaliq
    fonts:
      - asset: assets/fonts/NotoNastaliqUrdu-Regular.ttf
